// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetIDsRequest struct {
	Biz                  string   `protobuf:"bytes,1,opt,name=biz,proto3" json:"biz,omitempty"`
	Num                  int32    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIDsRequest) Reset()         { *m = GetIDsRequest{} }
func (m *GetIDsRequest) String() string { return proto.CompactTextString(m) }
func (*GetIDsRequest) ProtoMessage()    {}
func (*GetIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *GetIDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIDsRequest.Unmarshal(m, b)
}
func (m *GetIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIDsRequest.Marshal(b, m, deterministic)
}
func (m *GetIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIDsRequest.Merge(m, src)
}
func (m *GetIDsRequest) XXX_Size() int {
	return xxx_messageInfo_GetIDsRequest.Size(m)
}
func (m *GetIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIDsRequest proto.InternalMessageInfo

func (m *GetIDsRequest) GetBiz() string {
	if m != nil {
		return m.Biz
	}
	return ""
}

func (m *GetIDsRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GetIDsResponse struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	ErrCode              int32    `protobuf:"varint,3,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIDsResponse) Reset()         { *m = GetIDsResponse{} }
func (m *GetIDsResponse) String() string { return proto.CompactTextString(m) }
func (*GetIDsResponse) ProtoMessage()    {}
func (*GetIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetIDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIDsResponse.Unmarshal(m, b)
}
func (m *GetIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIDsResponse.Marshal(b, m, deterministic)
}
func (m *GetIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIDsResponse.Merge(m, src)
}
func (m *GetIDsResponse) XXX_Size() int {
	return xxx_messageInfo_GetIDsResponse.Size(m)
}
func (m *GetIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIDsResponse proto.InternalMessageInfo

func (m *GetIDsResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GetIDsResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetIDsResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func init() {
	proto.RegisterType((*GetIDsRequest)(nil), "model.GetIDsRequest")
	proto.RegisterType((*GetIDsResponse)(nil), "model.GetIDsResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xa9, 0x65, 0xab, 0x3b, 0xb0, 0x22, 0x41, 0xb1, 0x7a, 0x2a, 0xc5, 0x43, 0x2f, 0xb6,
	0xe0, 0xe2, 0x1f, 0x70, 0x17, 0x96, 0x3d, 0x78, 0xc9, 0xc1, 0x83, 0x17, 0xb1, 0xcd, 0x90, 0x8d,
	0x98, 0xcc, 0x9a, 0x49, 0x45, 0xfc, 0xf5, 0x92, 0x54, 0x0f, 0xee, 0xed, 0xf1, 0xf2, 0xde, 0xcb,
	0xc7, 0xc0, 0x82, 0xd1, 0x7f, 0x9a, 0x01, 0xdb, 0xbd, 0xa7, 0x40, 0x62, 0x66, 0x49, 0xe1, 0x7b,
	0xbd, 0x84, 0xc5, 0x06, 0xc3, 0x76, 0xcd, 0x12, 0x3f, 0x46, 0xe4, 0x20, 0xce, 0x20, 0xef, 0xcd,
	0x77, 0x99, 0x55, 0x59, 0x33, 0x97, 0x51, 0x46, 0xc7, 0x8d, 0xb6, 0x3c, 0xaa, 0xb2, 0x66, 0x26,
	0xa3, 0xac, 0x9f, 0xe0, 0xf4, 0xaf, 0xc4, 0x7b, 0x72, 0x8c, 0x31, 0x63, 0x14, 0x97, 0x59, 0x95,
	0x37, 0xb9, 0x8c, 0x52, 0x5c, 0xc2, 0x31, 0x7a, 0xff, 0x62, 0x59, 0xa7, 0xe6, 0x5c, 0x16, 0xe8,
	0xfd, 0x23, 0x6b, 0x71, 0x05, 0x27, 0xf1, 0x61, 0x20, 0x85, 0x65, 0x9e, 0x36, 0x63, 0x70, 0x45,
	0x0a, 0xef, 0x56, 0x00, 0xdb, 0xf5, 0x06, 0x1d, 0xfa, 0xd7, 0x80, 0xe2, 0x1e, 0x8a, 0xe9, 0x17,
	0x71, 0xde, 0x26, 0xd8, 0xf6, 0x1f, 0xe9, 0xf5, 0xc5, 0x81, 0x3b, 0xa1, 0x3c, 0xdc, 0x3c, 0xd7,
	0xda, 0x84, 0xdd, 0xd8, 0xb7, 0x03, 0xd9, 0xee, 0xed, 0x8b, 0x76, 0xae, 0x33, 0xea, 0x56, 0xff,
	0xce, 0x76, 0xa9, 0xd4, 0x17, 0xe9, 0x0a, 0xcb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x4e,
	0x69, 0x52, 0x16, 0x01, 0x00, 0x00,
}
